/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103408-g831718bbab-20210827"
#endif /* AVUTIL_FFVERSION_H */
