/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103439-ge07ada3dac-20210829"
#endif /* AVUTIL_FFVERSION_H */
