using System.Runtime.InteropServices;
using System.Windows;

// Version, Company, Product, etc. are generated by the SDK from MSBuild properties
// (-p:Version at release). Only the attributes the SDK does NOT generate live here.

[assembly: ComVisible(false)]

// WPF themed resources (Themes/Generic.xaml).
[assembly: ThemeInfo(
    ResourceDictionaryLocation.None,
    ResourceDictionaryLocation.SourceAssembly)]
