//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenRecorder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenRecorder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Cancel.
        /// </summary>
        public static string CaptureCancel {
            get {
                return ResourceManager.GetString("CaptureCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Cursor.
        /// </summary>
        public static string CaptureCursor {
            get {
                return ResourceManager.GetString("CaptureCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Display.
        /// </summary>
        public static string CaptureDisplay {
            get {
                return ResourceManager.GetString("CaptureDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Region.
        /// </summary>
        public static string CaptureRegion {
            get {
                return ResourceManager.GetString("CaptureRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture region by user selection.
        /// </summary>
        public static string CaptureRegionByUserSelection {
            get {
                return ResourceManager.GetString("CaptureRegionByUserSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Window.
        /// </summary>
        public static string CaptureWindow {
            get {
                return ResourceManager.GetString("CaptureWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete shortcut.
        /// </summary>
        public static string DeleteShortcut {
            get {
                return ResourceManager.GetString("DeleteShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display you set could not be found.
        /// </summary>
        public static string DisplayNotFound {
            get {
                return ResourceManager.GetString("DisplayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Bitrate.
        /// </summary>
        public static string EncoderAudioBitrate {
            get {
                return ResourceManager.GetString("EncoderAudioBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Codec.
        /// </summary>
        public static string EncoderAudioCodec {
            get {
                return ResourceManager.GetString("EncoderAudioCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Path.
        /// </summary>
        public static string EncoderBaseDirectory {
            get {
                return ResourceManager.GetString("EncoderBaseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Target.
        /// </summary>
        public static string EncoderCaptureDisplay {
            get {
                return ResourceManager.GetString("EncoderCaptureDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Format.
        /// </summary>
        public static string EncoderFileFormat {
            get {
                return ResourceManager.GetString("EncoderFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Rate.
        /// </summary>
        public static string EncoderFrameRate {
            get {
                return ResourceManager.GetString("EncoderFrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Settings.
        /// </summary>
        public static string EncoderSettings {
            get {
                return ResourceManager.GetString("EncoderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording (Pause).
        /// </summary>
        public static string EncoderStatusPauseMessage {
            get {
                return ResourceManager.GetString("EncoderStatusPauseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string EncoderStatusStartMessage {
            get {
                return ResourceManager.GetString("EncoderStatusStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for recording.
        /// </summary>
        public static string EncoderStatusStopMessage {
            get {
                return ResourceManager.GetString("EncoderStatusStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Bitrate.
        /// </summary>
        public static string EncoderVideoBitrate {
            get {
                return ResourceManager.GetString("EncoderVideoBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Codec.
        /// </summary>
        public static string EncoderVideoCodec {
            get {
                return ResourceManager.GetString("EncoderVideoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude app from capture..
        /// </summary>
        public static string ExcludeAppFromCapture {
            get {
                return ResourceManager.GetString("ExcludeAppFromCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start recording.
        /// </summary>
        public static string FailedToStartRecording {
            get {
                return ResourceManager.GetString("FailedToStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware encoder not found. Use a software encoder..
        /// </summary>
        public static string HardwareEncoderNotFoundWarning {
            get {
                return ResourceManager.GetString("HardwareEncoderNotFoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include app from capture..
        /// </summary>
        public static string IncludeAppFromCapture {
            get {
                return ResourceManager.GetString("IncludeAppFromCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a recording folder in File Explorer.
        /// </summary>
        public static string OpenEncodingFolderInFileExplorer {
            get {
                return ResourceManager.GetString("OpenEncodingFolderInFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a folder in File Explorer.
        /// </summary>
        public static string OpenFolderInFileExplorer {
            get {
                return ResourceManager.GetString("OpenFolderInFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Recording.
        /// </summary>
        public static string PauseRecording {
            get {
                return ResourceManager.GetString("PauseRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Display.
        /// </summary>
        public static string PrimaryDisplay {
            get {
                return ResourceManager.GetString("PrimaryDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording path does not exist.
        /// </summary>
        public static string RecordingPathDoesNotExist {
            get {
                return ResourceManager.GetString("RecordingPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Microphone.
        /// </summary>
        public static string RecordMicrophone {
            get {
                return ResourceManager.GetString("RecordMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region less than 100 x 100 cannot be recorded.
        /// </summary>
        public static string RegionSizeError {
            get {
                return ResourceManager.GetString("RegionSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the recording path.
        /// </summary>
        public static string SetsTheRecordingPath {
            get {
                return ResourceManager.GetString("SetsTheRecordingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Settings.
        /// </summary>
        public static string ShortcutSettings {
            get {
                return ResourceManager.GetString("ShortcutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording.
        /// </summary>
        public static string StartRecording {
            get {
                return ResourceManager.GetString("StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        public static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recording path is not set. Please set the recording path.
        /// </summary>
        public static string TheRecordingPathIsNotSet {
            get {
                return ResourceManager.GetString("TheRecordingPathIsNotSet", resourceCulture);
            }
        }
    }
}
